### ISSUE TITLE
[vitastor] vitastor often appears io hang

### ISSUE THREAD

**Issue by lnsyyj** [vitalif/vitastor#11]
When I installed the ubuntu18.04 system by mounting the optical drive through virtualization, the virtual machine stopped moving in the install kernel, and I saw the following log in syslog.

And has been stopped, it seems to be hanging, unable to continue.

```
Jul 12 16:59:57 vitastor-1 vitastor-osd[248596]: [OSD 2] avg latency for subop 15 (ping): 185 us
Jul 12 16:59:57 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=28 prog=536903814 vers=1 proc=6 type=0 status=0 serial=4689
Jul 12 16:59:57 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=188 prog=536903814 vers=1 proc=6 type=1 status=0 serial=4689
Jul 12 16:59:57 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=40 prog=536903814 vers=1 proc=344 type=0 status=0 serial=4690
Jul 12 16:59:57 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=3924 prog=536903814 vers=1 proc=344 type=1 status=0 serial=4690
Jul 12 16:59:59 vitastor-1 vitastor-osd[248623]: [OSD 1] avg latency for subop 15 (ping): 236 us
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34062 inode=1000000000004 offset=1280640000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34064 inode=1000000000004 offset=1280680000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34065 inode=1000000000004 offset=12806a0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34066 inode=1000000000004 offset=12806c0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34068 inode=1000000000004 offset=1280700000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34070 inode=1000000000004 offset=1280740000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34071 inode=1000000000004 offset=1280760000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34072 inode=1000000000004 offset=1280780000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34074 inode=1000000000004 offset=12807c0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34076 inode=1000000000004 offset=1280800000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34077 inode=1000000000004 offset=28800000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34079 inode=1000000000004 offset=28840000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34080 inode=1000000000004 offset=28860000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34081 inode=1000000000004 offset=28880000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34083 inode=1000000000004 offset=288c0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34085 inode=1000000000004 offset=28900000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34086 inode=1000000000004 offset=28920000 len=14000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34087 inode=1000000000004 offset=808c3d000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34088 inode=1000000000004 offset=808c3e000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34104 inode=1000000000004 offset=88a010000 len=8000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34121 inode=1000000000004 offset=808c3f000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34122 inode=1000000000004 offset=808c40000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34123 inode=1000000000004 offset=28620000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34124 inode=1000000000004 offset=808c41000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34125 inode=1000000000004 offset=808c42000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34126 inode=1000000000004 offset=808c43000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34127 inode=1000000000004 offset=808c45000 len=6000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34128 inode=1000000000004 offset=808c4b000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34129 inode=1000000000004 offset=808c4d000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34130 inode=1000000000004 offset=808c4f000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34131 inode=1000000000004 offset=808c50000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34132 inode=1000000000004 offset=808c51000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34133 inode=1000000000004 offset=808c52000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34134 inode=1000000000004 offset=808c53000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34135 inode=1000000000004 offset=28640000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34137 inode=1000000000004 offset=808c54000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34138 inode=1000000000004 offset=808c55000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34139 inode=1000000000004 offset=808c56000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34140 inode=1000000000004 offset=808c57000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34141 inode=1000000000004 offset=808c58000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34142 inode=1000000000004 offset=808c59000 len=5000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34143 inode=1000000000004 offset=808c5e000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34144 inode=1000000000004 offset=808c5f000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34151 inode=1000000000004 offset=28940000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34160 inode=1000000000004 offset=28700000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34162 inode=1000000000004 offset=28740000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34164 inode=1000000000004 offset=28780000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34165 inode=1000000000004 offset=287a0000 len=14000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34171 inode=1000000000004 offset=808c80000 len=5000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248623]: [OSD 1] Slow op from client 11: primary_write id=34172 inode=1000000000004 offset=808c85000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34061 inode=1000000000004 offset=1280620000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34063 inode=1000000000004 offset=1280660000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34067 inode=1000000000004 offset=12806e0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34069 inode=1000000000004 offset=1280720000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34073 inode=1000000000004 offset=12807a0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34075 inode=1000000000004 offset=12807e0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34078 inode=1000000000004 offset=28820000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34082 inode=1000000000004 offset=288a0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34084 inode=1000000000004 offset=288e0000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34136 inode=1000000000004 offset=28660000 len=12000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34145 inode=1000000000004 offset=808c60000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34146 inode=1000000000004 offset=808c61000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34147 inode=1000000000004 offset=808c62000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34148 inode=1000000000004 offset=808c63000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34149 inode=1000000000004 offset=808c64000 len=3000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34150 inode=1000000000004 offset=808c67000 len=3000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34152 inode=1000000000004 offset=28960000 len=a000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34153 inode=1000000000004 offset=808c6a000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34154 inode=1000000000004 offset=808c6c000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34155 inode=1000000000004 offset=808c6e000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34156 inode=1000000000004 offset=808c6f000 len=4000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34157 inode=1000000000004 offset=808c73000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34158 inode=1000000000004 offset=808c74000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34159 inode=1000000000004 offset=808c75000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34161 inode=1000000000004 offset=28720000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34163 inode=1000000000004 offset=28760000 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34166 inode=1000000000004 offset=808c76000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34167 inode=1000000000004 offset=808c77000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34168 inode=1000000000004 offset=808c78000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34169 inode=1000000000004 offset=808c79000 len=5000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 8: primary_write id=34170 inode=1000000000004 offset=808c7e000 len=2000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158793 1000000000004:1280640000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158795 1000000000004:1280680000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158797 1000000000004:12806a0000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158799 1000000000004:12806c0000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158801 1000000000004:1280700000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158803 1000000000004:1280740000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158805 1000000000004:1280760000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158807 1000000000004:1280780000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158809 1000000000004:12807c0000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158811 1000000000004:1280800000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158813 1000000000004:28800000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158815 1000000000004:28840000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158817 1000000000004:28860000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158819 1000000000004:28880000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158821 1000000000004:288c0000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158823 1000000000004:28900000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158825 1000000000004:28920000 v1 offset=0 len=14000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158827 1000000000004:808c20000 v10 offset=1d000 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158831 1000000000004:88a000000 v2 offset=10000 len=8000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158833 1000000000004:808c40000 v1 offset=0 len=1000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158835 1000000000004:28620000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158837 1000000000004:28640000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158839 1000000000004:28940000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158841 1000000000004:28700000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158843 1000000000004:28740000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158845 1000000000004:28780000 v1 offset=0 len=20000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158847 1000000000004:287a0000 v1 offset=0 len=14000
Jul 12 17:00:00 vitastor-1 vitastor-osd[248596]: [OSD 2] Slow op from client 10: write_stable id=158849 1000000000004:808c80000 v1 offset=0 len=5000
Jul 12 17:00:00 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=28 prog=536903814 vers=1 proc=6 type=0 status=0 serial=4691
Jul 12 17:00:00 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=188 prog=536903814 vers=1 proc=6 type=1 status=0 serial=4691
Jul 12 17:00:00 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=40 prog=536903814 vers=1 proc=344 type=0 status=0 serial=4692
Jul 12 17:00:00 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=3924 prog=536903814 vers=1 proc=344 type=1 status=0 serial=4692
Jul 12 17:00:02 vitastor-1 vitastor-osd[248623]: [OSD 1] avg latency for subop 15 (ping): 202 us
Jul 12 17:00:03 vitastor-1 vitastor-osd[248596]: [OSD 2] avg latency for subop 15 (ping): 232 us
Jul 12 17:00:03 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=28 prog=536903814 vers=1 proc=6 type=0 status=0 serial=4693
Jul 12 17:00:03 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=188 prog=536903814 vers=1 proc=6 type=1 status=0 serial=4693
Jul 12 17:00:03 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=40 prog=536903814 vers=1 proc=344 type=0 status=0 serial=4694
Jul 12 17:00:03 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=3924 prog=536903814 vers=1 proc=344 type=1 status=0 serial=4694
Jul 12 17:00:06 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=28 prog=536903814 vers=1 proc=6 type=0 status=0 serial=4695
Jul 12 17:00:06 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=188 prog=536903814 vers=1 proc=6 type=1 status=0 serial=4695
Jul 12 17:00:06 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_RX: client=0x555c3200e5a0 len=40 prog=536903814 vers=1 proc=344 type=0 status=0 serial=4696
Jul 12 17:00:06 vitastor-1 libvirtd[406644]: RPC_SERVER_CLIENT_MSG_TX_QUEUE: client=0x555c3200e5a0 len=3924 prog=536903814 vers=1 proc=344 type=1 status=0 serial=4696
Jul 12 17:00:08 vitastor-1 vitastor-osd[248623]: [OSD 1] avg latency for subop 15 (ping): 228 us
```

**Comment by vitalif** [comment]
Ok.. Are there any additional details in osd logs? Can you upload whole logs to pastebin? Is there enough space on osds?.. how much osds do you have, 3? And how are they configured?

**Comment by lnsyyj** [comment]
Yes, the OSD has enough space, 3 OSDs, 3.6TB per disk.

Does vitastor have its own log file?
pastebin does not seem to be able to upload logs larger than 512KB, So I upload the log here https://github.com/lnsyyj/vitastor-log.

```
root@vitastor-1:~# etcdctl --endpoints 192.168.3.100:2379 get "" --prefix
/vitastor/config/global
{"immediate_commit":"all"}
/vitastor/config/inode/1/1
{"name":"testimg","size":214748364800}
/vitastor/config/inode/1/2
{"name":"vitastor-inode-1","size":214748364800}
/vitastor/config/inode/1/3
{"name":"vitastor-inode-2","size":214748364800}
/vitastor/config/inode/1/4
{"name":"ubuntutestimg","size":214748364800}
/vitastor/config/pgs
{"hash":"983aff14943b369abd4158c9079333d6cc703667","items":{"1":{"1":{"osd_set":["1","2","3"],"primary":"1"},"2":{"osd_set":["1","2","3"],"primary":"2"},"3":{"osd_set":["1","2","3"],"primary":"1"},"4":{"osd_set":["1","2","3"],"primary":"1"},"5":{"osd_set":["1","2","3"],"primary":"1"},"6":{"osd_set":["1","2","3"],"primary":"2"}}}}
/vitastor/config/pools
{"1":{"name":"testpool","scheme":"replicated","pg_size":3,"pg_minsize":1,"pg_count":6,"failure_domain":"osd"}}
/vitastor/history/last_clean_pgs
{"hash":"983aff14943b369abd4158c9079333d6cc703667","items":{"1":{"1":{"osd_set":["1","2","3"],"primary":"1"},"2":{"osd_set":["1","2","3"],"primary":"2"},"3":{"osd_set":["1","2","3"],"primary":"1"},"4":{"osd_set":["1","2","3"],"primary":"1"},"5":{"osd_set":["1","2","3"],"primary":"1"},"6":{"osd_set":["1","2","3"],"primary":"2"}}}}
/vitastor/inode/stats/1/1
{"raw_used":"9403367424","read":{"count":"0","usec":"0","bytes":"0"},"write":{"count":"0","usec":"0","bytes":"0"},"delete":{"count":"0","usec":"0","bytes":"0"}}
/vitastor/inode/stats/1/2
{"raw_used":"292552704","read":{"count":"0","usec":"0","bytes":"0"},"write":{"count":"0","usec":"0","bytes":"0"},"delete":{"count":"0","usec":"0","bytes":"0"}}
/vitastor/inode/stats/1/4
{"raw_used":"23531618304","read":{"count":"11193","usec":"19889131","bytes":"330457088"},"write":{"count":"108267","usec":"8246348069","bytes":"7935225856"},"delete":{"count":"0","usec":"0","bytes":"0"}}
/vitastor/mon/master
{"ip":["192.168.3.100","192.168.122.1"]}
/vitastor/osd/inodestats/1
{"1": {"4": {"delete": {"bytes": 0, "count": 0, "usec": 0}, "read": {"bytes": 218812416, "count": 8046, "usec": 13027171}, "write": {"bytes": 5307723776, "count": 72158, "usec": 5731154729}}}}
/vitastor/osd/inodestats/2
{"1": {"4": {"delete": {"bytes": 0, "count": 0, "usec": 0}, "read": {"bytes": 111644672, "count": 3147, "usec": 6861960}, "write": {"bytes": 2627502080, "count": 36109, "usec": 2515193340}}}}
/vitastor/osd/inodestats/3
{}
/vitastor/osd/space/1
{"1": {"1": 3134455808, "2": 97517568, "4": 7843872768}}
/vitastor/osd/space/2
{"1": {"1": 3134455808, "2": 97517568, "4": 7843872768}}
/vitastor/osd/space/3
{"1": {"1": 3134455808, "2": 97517568, "4": 7843872768}}
/vitastor/osd/state/1
{"addresses": ["192.168.3.100"], "blockstore_enabled": true, "host": "vitastor-1", "port": 34877, "primary_enabled": true, "state": "up"}
/vitastor/osd/state/2
{"addresses": ["192.168.3.100"], "blockstore_enabled": true, "host": "vitastor-1", "port": 46301, "primary_enabled": true, "state": "up"}
/vitastor/osd/state/3
{"addresses": ["192.168.3.100"], "blockstore_enabled": true, "host": "vitastor-1", "port": 40581, "primary_enabled": true, "state": "up"}
/vitastor/osd/stats/1
{"blockstore_ready": true, "free": 3988716257280, "host": "vitastor-1", "op_stats": {"delete": {"bytes": 0, "count": 0, "usec": 0}, "list": {"bytes": 0, "count": 6, "usec": 34572}, "ping": {"bytes": 0, "count": 23973, "usec": 24444}, "primary_delete": {"bytes": 0, "count": 0, "usec": 0}, "primary_read": {"bytes": 218812416, "count": 8046, "usec": 13027171}, "primary_sync": {"bytes": 0, "count": 0, "usec": 0}, "primary_write": {"bytes": 5307723776, "count": 72114, "usec": 5730842846}, "read": {"bytes": 227463168, "count": 80044, "usec": 14036466}, "rollback": {"bytes": 0, "count": 0, "usec": 0}, "sec_read_bmp": {"bytes": 0, "count": 0, "usec": 0}, "show_config": {"bytes": 0, "count": 14, "usec": 290}, "stabilize": {"bytes": 0, "count": 0, "usec": 0}, "sync": {"bytes": 0, "count": 6, "usec": 19267523}, "sync_stab_all": {"bytes": 0, "count": 0, "usec": 0}, "write": {"bytes": 0, "count": 0, "usec": 0}, "write_stable": {"bytes": 2617802752, "count": 107989, "usec": 6194014115}}, "recovery_stats": {"degraded": {"bytes": 5767168, "count": 44}, "misplaced": {"bytes": 0, "count": 0}}, "size": 3999792365568, "subop_stats": {"delete": {"count": 0, "usec": 0}, "list": {"count": 12, "usec": 143580}, "ping": {"count": 23974, "usec": 5721007}, "primary_delete": {"count": 0, "usec": 0}, "primary_read": {"count": 0, "usec": 0}, "primary_sync": {"count": 0, "usec": 0}, "primary_write": {"count": 0, "usec": 0}, "read": {"count": 0, "usec": 0}, "rollback": {"count": 0, "usec": 0}, "sec_read_bmp": {"count": 0, "usec": 0}, "show_config": {"count": 4, "usec": 1094}, "stabilize": {"count": 0, "usec": 0}, "sync": {"count": 12, "usec": 31781129}, "sync_stab_all": {"count": 0, "usec": 0}, "write": {"count": 0, "usec": 0}, "write_stable": {"count": 143952, "usec": 9050297266}}, "time": "1626141364.733"}
/vitastor/osd/stats/2
{"blockstore_ready": true, "free": 3988716257280, "host": "vitastor-1", "op_stats": {"delete": {"bytes": 0, "count": 0, "usec": 0}, "list": {"bytes": 0, "count": 6, "usec": 13660}, "ping": {"bytes": 0, "count": 23973, "usec": 25165}, "primary_delete": {"bytes": 0, "count": 0, "usec": 0}, "primary_read": {"bytes": 111644672, "count": 3147, "usec": 6861960}, "primary_sync": {"bytes": 0, "count": 0, "usec": 0}, "primary_write": {"bytes": 2627502080, "count": 36087, "usec": 2514972620}, "read": {"bytes": 111644672, "count": 39138, "usec": 7309828}, "rollback": {"bytes": 0, "count": 0, "usec": 0}, "sec_read_bmp": {"bytes": 0, "count": 0, "usec": 0}, "show_config": {"bytes": 0, "count": 14, "usec": 303}, "stabilize": {"bytes": 0, "count": 0, "usec": 0}, "sync": {"bytes": 0, "count": 6, "usec": 24386975}, "sync_stab_all": {"bytes": 0, "count": 0, "usec": 0}, "write": {"bytes": 0, "count": 0, "usec": 0}, "write_stable": {"bytes": 5289635840, "count": 107989, "usec": 5838622797}}, "recovery_stats": {"degraded": {"bytes": 2883584, "count": 22}, "misplaced": {"bytes": 0, "count": 0}}, "size": 3999792365568, "subop_stats": {"delete": {"count": 0, "usec": 0}, "list": {"count": 6, "usec": 59384}, "ping": {"count": 23974, "usec": 5670767}, "primary_delete": {"count": 0, "usec": 0}, "primary_read": {"count": 0, "usec": 0}, "primary_sync": {"count": 0, "usec": 0}, "primary_write": {"count": 0, "usec": 0}, "read": {"count": 22, "usec": 101512}, "rollback": {"count": 0, "usec": 0}, "sec_read_bmp": {"count": 0, "usec": 0}, "show_config": {"count": 3, "usec": 802}, "stabilize": {"count": 0, "usec": 0}, "sync": {"count": 6, "usec": 8921334}, "sync_stab_all": {"count": 0, "usec": 0}, "write": {"count": 0, "usec": 0}, "write_stable": {"count": 72026, "usec": 3945960857}}, "time": "1626141367.084"}
/vitastor/osd/stats/3
{"blockstore_ready": true, "free": 3988716257280, "host": "vitastor-1", "op_stats": {"delete": {"bytes": 0, "count": 0, "usec": 0}, "list": {"bytes": 0, "count": 6, "usec": 29677}, "ping": {"bytes": 0, "count": 23974, "usec": 27676}, "primary_delete": {"bytes": 0, "count": 0, "usec": 0}, "primary_read": {"bytes": 0, "count": 0, "usec": 0}, "primary_sync": {"bytes": 0, "count": 0, "usec": 0}, "primary_write": {"bytes": 0, "count": 0, "usec": 0}, "read": {"bytes": 0, "count": 0, "usec": 0}, "rollback": {"bytes": 0, "count": 0, "usec": 0}, "sec_read_bmp": {"bytes": 0, "count": 0, "usec": 0}, "show_config": {"bytes": 0, "count": 2, "usec": 27}, "stabilize": {"bytes": 0, "count": 0, "usec": 0}, "sync": {"bytes": 0, "count": 6, "usec": 21057897}, "sync_stab_all": {"bytes": 0, "count": 0, "usec": 0}, "write": {"bytes": 0, "count": 0, "usec": 0}, "write_stable": {"bytes": 7907438592, "count": 107989, "usec": 6744321832}}, "recovery_stats": {"degraded": {"bytes": 0, "count": 0}, "misplaced": {"bytes": 0, "count": 0}}, "size": 3999792365568, "subop_stats": {"delete": {"count": 0, "usec": 0}, "list": {"count": 0, "usec": 0}, "ping": {"count": 0, "usec": 0}, "primary_delete": {"count": 0, "usec": 0}, "primary_read": {"count": 0, "usec": 0}, "primary_sync": {"count": 0, "usec": 0}, "primary_write": {"count": 0, "usec": 0}, "read": {"count": 0, "usec": 0}, "rollback": {"count": 0, "usec": 0}, "sec_read_bmp": {"count": 0, "usec": 0}, "show_config": {"count": 0, "usec": 0}, "stabilize": {"count": 0, "usec": 0}, "sync": {"count": 0, "usec": 0}, "sync_stab_all": {"count": 0, "usec": 0}, "write": {"count": 0, "usec": 0}, "write_stable": {"count": 0, "usec": 0}}, "time": "1626141369.372"}
/vitastor/pg/history/1/1
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/history/1/2
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/history/1/3
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/history/1/4
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/history/1/5
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/history/1/6
{"all_peers": [1, 2, 3], "epoch": 0, "osd_sets": []}
/vitastor/pg/state/1/1
{"peers": [1, 2, 3], "primary": 1, "state": ["active"]}
/vitastor/pg/state/1/2
{"peers": [1, 2, 3], "primary": 2, "state": ["active"]}
/vitastor/pg/state/1/3
{"peers": [1, 2, 3], "primary": 1, "state": ["active"]}
/vitastor/pg/state/1/4
{"peers": [1, 2, 3], "primary": 1, "state": ["active"]}
/vitastor/pg/state/1/5
{"peers": [1, 2, 3], "primary": 1, "state": ["active"]}
/vitastor/pg/state/1/6
{"peers": [1, 2, 3], "primary": 2, "state": ["active"]}
/vitastor/pg/stats/1/1
{"clean_count": 14164, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14164, "write_osd_set": [1, 2, 3]}
/vitastor/pg/stats/1/2
{"clean_count": 14027, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14027, "write_osd_set": [1, 2, 3]}
/vitastor/pg/stats/1/3
{"clean_count": 14140, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14140, "write_osd_set": [1, 2, 3]}
/vitastor/pg/stats/1/4
{"clean_count": 14001, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14001, "write_osd_set": [1, 2, 3]}
/vitastor/pg/stats/1/5
{"clean_count": 14148, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14148, "write_osd_set": [1, 2, 3]}
/vitastor/pg/stats/1/6
{"clean_count": 14022, "degraded_count": 0, "incomplete_count": 0, "misplaced_count": 0, "object_count": 14022, "write_osd_set": [1, 2, 3]}
/vitastor/stats
{"op_stats":{"delete":{"count":"0","usec":"0","bytes":"0"},"list":{"count":"18","usec":"77909","bytes":"0"},"ping":{"count":"71920","usec":"77285","bytes":"0"},"primary_delete":{"count":"0","usec":"0","bytes":"0"},"primary_read":{"count":"11193","usec":"19889131","bytes":"330457088"},"primary_sync":{"count":"0","usec":"0","bytes":"0"},"primary_write":{"count":"108201","usec":"8245815466","bytes":"7935225856"},"read":{"count":"119182","usec":"21346294","bytes":"339107840"},"rollback":{"count":"0","usec":"0","bytes":"0"},"sec_read_bmp":{"count":"0","usec":"0","bytes":"0"},"show_config":{"count":"30","usec":"620","bytes":"0"},"stabilize":{"count":"0","usec":"0","bytes":"0"},"sync":{"count":"18","usec":"64712395","bytes":"0"},"sync_stab_all":{"count":"0","usec":"0","bytes":"0"},"write":{"count":"0","usec":"0","bytes":"0"},"write_stable":{"count":"323967","usec":"18776958744","bytes":"15814877184"}},"subop_stats":{"delete":{"count":"0","usec":"0"},"list":{"count":"18","usec":"202964"},"ping":{"count":"47948","usec":"11391774"},"primary_delete":{"count":"0","usec":"0"},"primary_read":{"count":"0","usec":"0"},"primary_sync":{"count":"0","usec":"0"},"primary_write":{"count":"0","usec":"0"},"read":{"count":"22","usec":"101512"},"rollback":{"count":"0","usec":"0"},"sec_read_bmp":{"count":"0","usec":"0"},"show_config":{"count":"7","usec":"1896"},"stabilize":{"count":"0","usec":"0"},"sync":{"count":"18","usec":"40702463"},"sync_stab_all":{"count":"0","usec":"0"},"write":{"count":"0","usec":"0"},"write_stable":{"count":"215978","usec":"12996258123"}},"recovery_stats":{"degraded":{"count":"66","bytes":"8650752"},"misplaced":{"count":"0","bytes":"0"}},"object_counts":{"object":"84502","clean":"84502","misplaced":"0","degraded":"0","incomplete":"0"}}
```

**Comment by vitalif** [comment]
There is no log file option, but when I need to write the log to a separate file I usually just change the systemd units like
```
ExecStart=bash -c 'vitastor-osd \
    ....\
    >>/var/log/vitastor/osd1.log 2>&1'
```
:-)

**Comment by vitalif** [comment]
The last entry in the log from the third was timed 16:15:48 and then it stopped reporting... Did anything strange happen with it?) like hanging with 100% cpu usage or something like that.
Do you say it happens after you install Ubuntu from ISO? I can try to do the same probably to reproduce the problem...

**Comment by vitalif** [comment]
By the way: did you start your osds with `--journal_no_same_sector_overwrites true --journal_sector_buffer_count 1024 --disable_data_fsync 1 --immediate_commit all` options? These are required if you have global `immediate_commit: all` setting. In fact first two are optional, but disable_fsync+immediate_commit are required

**Comment by lnsyyj** [comment]
Yes, this is my osd systemd units.

```
root@vitastor-1:~# systemctl cat vitastor-osd1.service 
# /etc/systemd/system/vitastor-osd1.service
[Unit]
Description=Vitastor object storage daemon osd.1
After=network-online.target local-fs.target time-sync.target
Wants=network-online.target local-fs.target time-sync.target
PartOf=vitastor.target

[Service]
LimitNOFILE=1048576
LimitNPROC=1048576
LimitMEMLOCK=infinity
ExecStart=/usr/bin/vitastor-osd \
    --etcd_address 192.168.3.100:2379/v3 \
    --bind_address 192.168.3.100 \
    --osd_num 1 \
    --disable_data_fsync 1 \
    --immediate_commit all \
    --disk_alignment 4096 --journal_block_size 4096 --meta_block_size 4096 \
    --journal_no_same_sector_overwrites true \
    --journal_sector_buffer_count 1024 \
        --data_device /dev/disk/by-partuuid/22fdbb7e-913c-40c0-b3e4-1c80978d2326     --journal_offset 0     --meta_offset 16777216     --data_offset 993533952 
WorkingDirectory=/
ExecStartPre=+chown vitastor:vitastor /dev/disk/by-partuuid/22fdbb7e-913c-40c0-b3e4-1c80978d2326
User=vitastor
PrivateTmp=false
TasksMax=infinity
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=vitastor.target
```

> By the way: did you start your osds with `--journal_no_same_sector_overwrites true --journal_sector_buffer_count 1024 --disable_data_fsync 1 --immediate_commit all` options? These are required if you have global `immediate_commit: all` setting. In fact first two are optional, but disable_fsync+immediate_commit are required

**Comment by lnsyyj** [comment]
> The last entry in the log from the third was timed 16:15:48 and then it stopped reporting... Did anything strange happen with it?) like hanging with 100% cpu usage or something like that.
> Do you say it happens after you install Ubuntu from ISO? I can try to do the same probably to reproduce the problem...

I didn't observe the CPU and other strange things at the time. During the process of installing ubuntu from the ISO, the problem occurred during the install kernel step, and it hangs for about 20 minutes. After discovering this problem, I restarted each vitastor-osd.service, and then IO continued.
I think this is not 100% reproducible, it may take a few more attempts.

**Comment by vitalif** [comment]
Interesting, I tried to install debian yesterday, it worked without any problems

**Comment by vitalif** [comment]
Maybe I'll make some changes to slow ops dumper so it shows their states to better understand what's going on based on logs...

**Comment by lnsyyj** [comment]
That's great, I met it twice today.
I am currently using 0.6.4. Will 0.6.5 improve?

**Comment by vitalif** [comment]
I don't think 0.6.5 will make any difference given that you encounter such hangs...

**Comment by vitalif** [comment]
Try to install 0.6.6-dev build from `deb https://vitastor.io/debian bullseye-dev main` and check the logs, I added operation state dumping in this build

**Comment by lnsyyj** [comment]
Can I use the master branch on github to compile and install?

**Comment by lnsyyj** [comment]
I updated the log to: https://github.com/lnsyyj/vitastor-log/blob/main/vitastor-osd-new.log

**Comment by vitalif** [comment]
Ok, it seems I have to add more diagnostics :) I'll probably try to add journal flusher diagnostics dump when there is at least 1 slow op.
Your problem is caused by journal flusher stopping at some point and not being able to resume, either because it ignores a resume request due to some race condition, or because something prevents it to purge old data.
The simple solution is to just increase journal size, but please don't do it yet because I want to catch the bug :)

**Comment by lnsyyj** [comment]
Waiting for your good news. I am very interested. But I don't fully understand the code now. 
If necessary, I will cooperate with you to test.

**Comment by vitalif** [comment]
> Waiting for your good news. I am very interested. But I don't fully understand the code now.
> If necessary, I will cooperate with you to test.

As of now, you can uncomment `#define BLOCKSTORE_DEBUG` in blockstore_impl.h, rebuild the project and retry. And you should redirect logs to files by wrapping ExecStart into `bash -c ""` as I wrote above because there'll be A LOT of them and journald will definitely drop some of the messages. Then try to reproduce the bug and send me the logs... they'll be super-detailed, so there should be something interesting.

**Comment by vitalif** [comment]
I added some more diagnostics to the slow ops log, please build from master and recheck

**Comment by lnsyyj** [comment]
Hi @vitalif ,
I updated the log to: https://github.com/lnsyyj/vitastor-log
BLOCKSTORE_DEBUG_log.tar.gz

**Comment by vitalif** [comment]
Ok, thanks, I think I fixed this issue, please rebuild from master and retry :-)

**Comment by lnsyyj** [comment]
Hi @vitalif ,
The IO hang problem still exists, but there is no need to restart the OSD. When my virtual machine was reading and writing, io hang took about tens of seconds, and then suddenly recovered by itself, and it happened frequently.

**Comment by vitalif** [comment]
In all previous logs the hang happen on OSD2. Is it still the case? Maybe that SSD is bad? You can try to check two replica pool with osd 1 & 3... if it doesn't hang it may mean there is a problem with the ssd. Maybe that's even why you hit the bug which I fixed in the first place?..

**Comment by lnsyyj** [comment]
I use 3 HDDs and smartctl reports that the hard drives are good, but no abnormalities are found. I will try to open the vitastor log again to see if there are new discoveries.

**Comment by vitalif** [comment]
HDDs... unstable IO is normal for vitastor on HDD without at least SSD journal&meta. You should use an SSD for metadata and block_size 4MB

**Comment by lnsyyj** [comment]
Okay, I am going to use two nvme to try.

**Comment by lnsyyj** [comment]
Hi @vitalif ,
The problem is that my virtual machine's mac address conflict caused it to freeze, and now vitastor seems to be running well. Thank you! O(∩_∩)O

**Comment by vitalif** [comment]
Ok, so this issue seems resolved, fine
